INSERT INTO fatu_situacaocofins (codigofiscal, descricao) VALUES
("01", "OPERACAO TRIBUTAVEL COM ALIQUOTA BASICA");
INSERT INTO fatu_situacaocofins (codigofiscal, descricao) VALUES
("02", "OPERACAO TRIBUTAVEL COM ALIQUOTA DIFERENCIDADA");
INSERT INTO fatu_situacaocofins (codigofiscal, descricao) VALUES
("03", "OPERACAO TRIBUTAVEL COM ALIQUOTA POR UNIDADE DE MEDIDA DE PRODUTO");
INSERT INTO fatu_situacaocofins (codigofiscal, descricao) VALUES
("04", "OPERACAO TRIBUTAVEL MONOFASICA - REVENDA A LIQUOTA ZERO");
INSERT INTO fatu_situacaocofins (codigofiscal, descricao) VALUES
("05", "OPERACAO TRIBUTAVEL POR SUBSTITUICAO TRIBUTARIA");
INSERT INTO fatu_situacaocofins (codigofiscal, descricao) VALUES
("06", "OPERACAO TRIBUTAVEL A LIQUOTA ZERO");
INSERT INTO fatu_situacaocofins (codigofiscal, descricao) VALUES
("07", "OPERACAO ISENTA DA CONTRIBUICAO");
INSERT INTO fatu_situacaocofins (codigofiscal, descricao) VALUES
("08", "OPERACAO SEM INCIDENCIA DA CONTRIBUICAO");
INSERT INTO fatu_situacaocofins (codigofiscal, descricao) VALUES
("09", "OPERACAO COM SUSPENSAO DA CONTRIBUICAO");
INSERT INTO fatu_situacaocofins (codigofiscal, descricao) VALUES
("49", "OUTRAS OPERAÇOES DE SAIDA");
INSERT INTO fatu_situacaocofins (codigofiscal, descricao) VALUES
("50", "OPERACAO COM DIREITO A CREDITO - VINCULADA EXCLUSIVAMENTE A RECEITA TRIBUTADA NO MERCADO INTERNO");
INSERT INTO fatu_situacaocofins (codigofiscal, descricao) VALUES
("51", "OPERACAO COM DIREITO A CREDITO - VINCULADA EXCLUSIVAMENTE A RECEITA NAO-TRIBUTADA NO MERCADO INTERNO");
INSERT INTO fatu_situacaocofins (codigofiscal, descricao) VALUES
("52", "OPERACAO COM DIREITO A CREDITO - VINCULADA EXCLUSIVAMENTE A RECEITA DE EXPORTACAO");
INSERT INTO fatu_situacaocofins (codigofiscal, descricao) VALUES
("53", "OPERACAO COM DIREITO A CREDITO - VINCULADA A RECEITA TRIBUTADAS E NAO-TRIBUTADAS NO MERCADO INTERNO");
INSERT INTO fatu_situacaocofins (codigofiscal, descricao) VALUES
("54", "OPERACAO COM DIREITO A CREDITO - VINCULADA A RECEITAS TRIBUTADAS NO MERCADO INTERNO E DE EXPORTACAO");
INSERT INTO fatu_situacaocofins (codigofiscal, descricao) VALUES
("55", "OPERACAO COM DIREITO A CREDITO - VINCULADA A RECEITAS NAO TRIBUTADAS NO MERCADO INTERNO E DE EXPORTACAO");
INSERT INTO fatu_situacaocofins (codigofiscal, descricao) VALUES
("56", "OPERACAO COM DIREITO A CREDITO - VINCULADA A RECEITAS TRIBUDAS E NAO-TRIBUTADAS NO MERCADO INTERNO E DE EXPORTACAO");
INSERT INTO fatu_situacaocofins (codigofiscal, descricao) VALUES
("60", "CREDITO PRESUMIDO - OPERACAO DE AQUISICAO VINCULADA EXCLUSIVAMENTE A RECEITA TRIBUTADA NO MERCADO INTERNO");
INSERT INTO fatu_situacaocofins (codigofiscal, descricao) VALUES
("61", "CREDITO PRESUMIDO - OPERACAO DE AQUISICAO VINCULADA EXCLUSIVAMENTE A RECEITA NAO-TRIBUTADA NO MERCADO INTERNO");
INSERT INTO fatu_situacaocofins (codigofiscal, descricao) VALUES
("62", "CREDITO PRESUMIDO - OPERACAO DE AQUISICAO VINCULADA EXCLUSIVAMENTE A RECEITA DE EXPORTACAO");
INSERT INTO fatu_situacaocofins (codigofiscal, descricao) VALUES
("63", "CREDITO PRESUMIDO - OPERACAO DE AQUISICAO VINCULADA A RECEITAS TRIBUTADAS E NAO-TRIBUTADAS NO MERCADO INTERNO");
INSERT INTO fatu_situacaocofins (codigofiscal, descricao) VALUES
("64", "CREDITO PRESUMIDO - OPERACAO DE AQUISICAO VINCULADA A RECEITAS TRIBUTADAS NO MERCADO INTERNO E DE EXPORTACAO");
INSERT INTO fatu_situacaocofins (codigofiscal, descricao) VALUES
("65", "CREDITO PRESUMIDO - OPERACAO DE AQUISICAO VINCULADA A RECEITAS NAO-TRIBUTADAS NO MERCADO INTERNO E DE EXPORTACAO");
INSERT INTO fatu_situacaocofins (codigofiscal, descricao) VALUES
("66", "CREDITO PRESUMIDO - OPERACAO DE AQUISICAO VINCULADA A RECEITAS TRIBUTADAS E NAO-TRIBUTADAS NO MERCADO INTERNO E DE EXPORTACAO");
INSERT INTO fatu_situacaocofins (codigofiscal, descricao) VALUES
("67", "CREDITO PRESUMIDO - OUTRAS OPERACOES");
INSERT INTO fatu_situacaocofins (codigofiscal, descricao) VALUES
("70", "OPERACAO DE AQUISICAO SEM DIREITO A CREDITO");
INSERT INTO fatu_situacaocofins (codigofiscal, descricao) VALUES
("71", "OPERACAO DE AQUISICAO COM INSENCAO");
INSERT INTO fatu_situacaocofins (codigofiscal, descricao) VALUES
("72", "OPERACAO DE AQUISICAO COM SUSPENSAO");
INSERT INTO fatu_situacaocofins (codigofiscal, descricao) VALUES
("73", "OPERACAO DE AQUISICAO COM A ALIQUOTA ZERO");
INSERT INTO fatu_situacaocofins (codigofiscal, descricao) VALUES
("74", "OPERACAO DE AQUISICAO SEM INCIDENCIA DA CONTRIBUICAO");
INSERT INTO fatu_situacaocofins (codigofiscal, descricao) VALUES
("75", "OPERACAO DE AQUISICAO POR SUBSTITUICAO TRIBUTARIA");
INSERT INTO fatu_situacaocofins (codigofiscal, descricao) VALUES
("98", "OUTRAS OPERACOES DE ENTRADA");
INSERT INTO fatu_situacaocofins (codigofiscal, descricao) VALUES
("99", "OUTRAS OPERACOES");


INSERT INTO fatu_situacaopis (codigofiscal, descricao) values
("01", "OPERACAO TRIBUTAVEL COM ALIQUOTA BASICA");
INSERT INTO fatu_situacaopis (codigofiscal, descricao) values
("02", "OPERACAO TRIBUTAVEL COM ALIQUOTA DIFERENCIADA");
INSERT INTO fatu_situacaopis (codigofiscal, descricao) values
("03", "OPERACAO TRIBUTAVEL COM ALIQUOTA POR UNIDADE DE MEDIDA DE PRODUTO");
INSERT INTO fatu_situacaopis (codigofiscal, descricao) values
("04", "OPERACAO TRIBUTAVEL MONOFASICA - REVENDA A ALIQUOTA ZERO");
INSERT INTO fatu_situacaopis (codigofiscal, descricao) values
("05", "OPERACAO TRIBUTAVEL POR SUBSTITUICAO TRIBUTARIA");
INSERT INTO fatu_situacaopis (codigofiscal, descricao) values
("06", "OPERACAO TRIBUTAVEL A ALIQUOTA ZERO");
INSERT INTO fatu_situacaopis (codigofiscal, descricao) values
("07", "OPERACAO ISENTA DA CONTRIBUICAO");
INSERT INTO fatu_situacaopis (codigofiscal, descricao) values
("08", "OPERACAO SEM INCIDENCIA DA CONTRIBUICAO");
INSERT INTO fatu_situacaopis (codigofiscal, descricao) values
("09", "OPERACAO COM SUSPENSAO DA CONTRIBUICAO");
INSERT INTO fatu_situacaopis (codigofiscal, descricao) values
("49", "OUTRAS OPERACOES DE SAIDA");
INSERT INTO fatu_situacaopis (codigofiscal, descricao) values
("50", "OPERACAO COM DIREITO A CREDITO - VINCULADA EXCLUSIVAMENTE A RECEITA TRIBUTADA NO MERCADO INTERNO");
INSERT INTO fatu_situacaopis (codigofiscal, descricao) values
("51", "OPERACAO COM DIREITO A CREDITO - VINCULADA EXCLUSIVAMENTE A RECEITA NAO TRIBUTADA NO MERCADO INTERNO");
INSERT INTO fatu_situacaopis (codigofiscal, descricao) values
("52", "OPERACAO COM DIREITO A CREDITO - VINCULADA EXCLUSIVAMENTE A RECEITA DE EXPORTACAO");
INSERT INTO fatu_situacaopis (codigofiscal, descricao) values
("53", "OPERACAO COM DIREITO A CREDITO - VINCULADA A RECEITAS TRIBUTADAS E NAO-TRIBUTADAS NO MERCADO INTERNO");
INSERT INTO fatu_situacaopis (codigofiscal, descricao) values
("54", "OPERACAO COM DIREITO A CREDITO - VINCULADA A RECEITAS TRIBUTADAS NO MERCADO INTERNO E DE EXPORTACAO");
INSERT INTO fatu_situacaopis (codigofiscal, descricao) values
("55", "OPERACAO COM DIREITO A CREDITO - VINCULADA A RECEITAS NAO-TRIBUTADAS NO MERCADO INTERNO E DE EXPORTACAO");
INSERT INTO fatu_situacaopis (codigofiscal, descricao) values
("56", "OPERACAO COM DIREITO A CREDITO - VINCULADA A RECEITAS TRIBUTADAS NO MERCADO INTERNO, E DE EXPORTACAO");
INSERT INTO fatu_situacaopis (codigofiscal, descricao) values
("60", "CREDITO PRESUMIDO - OPERACAO DE AQUISICAO VINCULADA EXCLUSIVAMENTE A RECEITA TRIBUTADA NO MERCADO INTERNO");
INSERT INTO fatu_situacaopis (codigofiscal, descricao) values
("61", "CREDITO PRESUMIDO - OPERACAO DE AQUISICAO VINCULADA EXCLUSIVAMENTE A RECEITA NAO-TRIBUTADA NO MERCADO INTERNO");
INSERT INTO fatu_situacaopis (codigofiscal, descricao) values
("62", "CREDITO PRESUMIDO - OPERACAO DE AQUISICAO VINCULADA EXCLUSIVAMENTE A RECEITA DE EXPORTACAO");
INSERT INTO fatu_situacaopis (codigofiscal, descricao) values
("63", "CREDITO PRESUMIDO - OPERACAO DE AQUISICAO VINCULADA A RECEITAS TRIBUTADAS E NAO-TRIBUTADAS NO MERCADO INTERNO");
INSERT INTO fatu_situacaopis (codigofiscal, descricao) values
("64", "CREDITO PRESUMIDO - OPERACAO DE AQUISICAO VINCULADA A RECEITAS TRIBUTADAS NO MERCADO INTERNO E DE EXPORTACAO");
INSERT INTO fatu_situacaopis (codigofiscal, descricao) values
("65", "CREDITO PRESUMIDO - OPERACAO DE AQUISICAO VINCULADA A RECEITAS NAO-TRIBUTADAS NO MERCADO INTERNO E DE EXPORTACAO");
INSERT INTO fatu_situacaopis (codigofiscal, descricao) values
("66", "CREDITO PRESUMIDO - OPERACAO DE AQUISICAO VINCULADA A RECEITAS TRIBUTADAS E NAO-TRIBUTADAS NO MERCADO INTERNO, E DE EXPORTACAO");
INSERT INTO fatu_situacaopis (codigofiscal, descricao) values
("67", "CREDITO PRESUMIDO - OUTRAS OPERACOES");
INSERT INTO fatu_situacaopis (codigofiscal, descricao) values
("70", "OPERACAO DE AQUISICAO SEM DIREITO A CREDITO");
INSERT INTO fatu_situacaopis (codigofiscal, descricao) values
("71", "OPERACAO DE AQUISICAO COM INSENCAO");
INSERT INTO fatu_situacaopis (codigofiscal, descricao) values
("72", "OPERACAO DE AQUISICAO COM SUSPENSAO");
INSERT INTO fatu_situacaopis (codigofiscal, descricao) values
("73", "OPERACAO DE AQUISICAO A ALIQUOTA ZERO");
INSERT INTO fatu_situacaopis (codigofiscal, descricao) values
("74", "OPERACAO DE AQUISICAO SEM INCIDENCIA DA CONTRIBUICAO");
INSERT INTO fatu_situacaopis (codigofiscal, descricao) values
("75", "OPERACAO DE AQUISICAO POR SUBSTITUICAO TRIBUTARIA");
INSERT INTO fatu_situacaopis (codigofiscal, descricao) values
("98", "OUTRAS OPERACOES DE ENTRADA");
INSERT INTO fatu_situacaopis (codigofiscal, descricao) values
("99", "OUTRAS OPERACOES");